name: puppeteer_dart
description: Puppeteer is a Node library which provides a high-level API to control headless Chrome over the DevTools Protocol. It can also be configured to use full (non-headless) Chrome.
version: 0.0.1
#homepage: https://www.example.com
#author: xavier.hainaux <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  meta:

dev_dependencies:
  test: ^0.12.0
  dart_style: