name: chrome_dev_tools
description: An API to control headless Chrome over the DevTools Protocol.
version: 0.0.1
homepage: https://github.com/xavierhainaux/puppeteer-dart
author: xavier.hainaux <xavier.hainaux@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  meta:

dev_dependencies:
  test: ^0.12.0
  dart_style: